apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: gremlin.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: runs Gremlin on OpenShift
  displayName: Gremlin
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gremlin
  links:
  - name: Gremlin
    url: https://gremlin.domain
  maintainers:
  - email: patrickabrennan@gmail.com
    name: Patrick Brennan
  maturity: alpha
  provider:
    name: gremlin
  version: 0.0.0
